import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from '@/components/ui/sonner'
import { ReactQueryProvider } from "./ReactQueryProvider";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = { title: "Hiplando", description: "Generated by create next app" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html suppressHydrationWarning lang="en">
            <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans max-w-screen`}>
                <ThemeProvider attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange>
                    <AuthProvider>
                        <Toaster
                            closeButton
                            expand
                            richColors
                            offset={{ top: 60 }}
                            mobileOffset={{ top: 70 }}
                            position="top-right"
                        />
                        <ReactQueryProvider>
                            {children}
                        </ReactQueryProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}